version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    volumes:
      - ./tests:/tests
    depends_on:
      - api
    command: ["pytest", "/tests"]
